version: '3'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo01
    volumes:
      - ~/docker/data/mongodb:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"

#  mongo-express:
#    image: mongo-express
#    restart: always
#    container_name: mongomgr01
#    ports:
#      - '8081:8081'
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 123

